package step_definitions;

import io.cucumber.java.After;
import io.cucumber.java.Before;
import io.cucumber.java.Scenario;
import utils.CommonMethods;
import utils.ConfigReader;
import utils.DatabaseUtils;
import utils.DriverUtils;

import javax.xml.crypto.Data;

public class Hooks {
    @Before
    public void setUp(Scenario scenario){
        ConfigReader.initializeProperties();
        DatabaseUtils.initializeDBProperties();
        DriverUtils.createDriver(scenario);
    }
    @After
    public void cleanUp(Scenario scenario){
        DatabaseUtils.closeDataBaseConnection();
        try {
            Thread.sleep(3500);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        //Here we are using the scenario.attach() method in order to attach our screenshot to the scenario
        //The parameters we are passing is the byte[] array screenshot which is generated by the takeScreenshot method
        //The media type image/png since this is an image of png type
        //and the name of the scenario as the name of the image
        //if scenario is failed then we gonna take a screenshot
        if(scenario.isFailed()){
            scenario.attach(CommonMethods.takeScreenshot(),"image/png",scenario.getName());
        }
        CommonMethods.takeScreenshot(scenario);
        DriverUtils.quitDriver(scenario);
    }
}